export const structDataDesinc = {
    folio: "",
    linea: "",
    solicita: "",
    informa: "",
    estacion: "",
    sentido:"",
    economico: "",
    empresa: "",
    motivo: "",
    odometro: "",
    credencial: "",
    nombre: "",
    fecha: new Date(),
    hora: new Date().getHours(),
    jornada: new Date().getHours(),
    observaciones: "",
    tipo: "",
    edoFolio: "",
    tree: "",
    ida: "",
    regreso: ""
};